preferred_solution_number: 1
tool_mass: 1.75
bigger_pulley_bearing_position: [-0.739757210413974, 0.07993900394775277, 0.2449995438351456, -0.7217029684216122, -1.7591780460014375, 1.7685571865188172]
initial_joint_states : [2.97326, -1.6538, -2.33488, -2.28384, -2.53001, -3.13221] # for gazebo
task_initial_position: [-0.13, 0, -0.04, 0,0,0] # in relative to bigger pulley bearing's frame.

#force controller gain
f_x_kp : 0.00007
f_x_ki : 0
f_x_kd : 0

f_y_kp : 0
f_y_ki : 0
f_y_kd : 0

f_z_kp : 0
f_z_ki : 0
f_z_kd : 0

f_eaa_x_kp : 0
f_eaa_x_ki : 0
f_eaa_x_kd : 0

f_eaa_y_kp : 0
f_eaa_y_ki : 0
f_eaa_y_kd : 0

f_eaa_z_kp : 0
f_eaa_z_ki : 0
f_eaa_z_kd : 0

#position controller gain
p_x_kp : 0.7 #0.6
p_x_ki : 0
p_x_kd : 0

p_y_kp : 0
p_y_ki : 0
p_y_kd : 0

p_z_kp : 0
p_z_ki : 0
p_z_kd : 0

p_eaa_x_kp : 0
p_eaa_x_ki : 0
p_eaa_x_kd : 0

p_eaa_y_kp : 0
p_eaa_y_ki : 0
p_eaa_y_kd : 0

p_eaa_z_kp : 0
p_eaa_z_ki : 0
p_eaa_z_kd : 0


